<a href='https://github.com/angular/angular.js/edit/v1.8.x/docs/content/error/$interval/badprom.ngdoc?message=docs(error%2Fbadprom)%3A%20describe%20your%20change...' class='improve-docs btn btn-primary'><i class="glyphicon glyphicon-edit">&nbsp;</i>Improve this Doc</a>


<h1>Error: $interval:badprom
  <div><span class='hint'>Non-$interval promise</span></div>
</h1>

<div>
    <pre class="minerr-errmsg" error-display="`$interval.cancel()` called with a promise that was not generated by `$interval()`.">`$interval.cancel()` called with a promise that was not generated by `$interval()`.</pre>
</div>

<h2 id="description">Description</h2>
<div class="description">
  <p>This error occurs when calling <a href="api/ng/service/$interval#cancel">$interval.cancel()</a> with a promise that
was not generated by the <a href="api/ng/service/$interval">$interval</a> service. This can, for example, happen when
calling <a href="api/ng/service/$q#the-promise-api">then()/catch()</a> on the returned promise, which creates a new
promise, and pass that new promise to <a href="api/ng/service/$interval#cancel">$interval.cancel()</a>.</p>
<p>Example of incorrect usage that leads to this error:</p>
<pre><code class="lang-js">var promise = $interval(doSomething, 1000, 5).then(doSomethingElse);
$interval.cancel(promise);
</code></pre>
<p>To fix the example above, keep a reference to the promise returned by
<a href="api/ng/service/$interval">$interval()</a> and pass that to <a href="api/ng/service/$interval#cancel">$interval.cancel()</a>:</p>
<pre><code class="lang-js">var promise = $interval(doSomething, 1000, 5);
var newPromise = promise.then(doSomethingElse);
$interval.cancel(promise);
</code></pre>

</div>


